name = "cobol-site"
type = "webpack"
account_id = "6bf9a4aaa894d38962d0bd8fd4a98f10"
workers_dev = false
route = "cobol.speedcf.com/*"
zone_id = "94a53dfbf824bef82b5f40333d627168"

[site]
bucket = "./public"
